import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { computeImageAnchors } from "./image-placement.ts";
import { DivyaDesamSchema } from "../../content-lib/schemas/index.ts";

/**
 * Third post-Phase-6E-C review pass: "the positioning of the pictures
 * is still not happening correctly." The earlier fix (fix-image-
 * issues.ts) only split images into two buckets -- before/after Sthala
 * Puranam -- which was itself an improvement over "everything at the
 * top," but records with SEVERAL named sub-sections (Singavelkundram/
 * Ahobilam's nine Narasimha forms, Tirudwarkai's Beyt/Dakor/Shrinathji
 * sub-temples) still had every "after" image lumped into one
 * undifferentiated group instead of sitting next to the specific
 * sub-heading it illustrates.
 *
 * This pass runs AFTER duplicate removal and coarse placement (it reads
 * the CURRENT, already-corrected images[] arrays) and sets the new
 * `placementAnchor` field (content-lib/schemas/shared.ts) wherever
 * image-placement.ts's `computeImageAnchors` can confidently identify
 * which specific line of `sthalaPuranam` an image belongs after. Only
 * applies to original SAP images with `placement: "after-sthala-
 * puranam"` already set -- book images have no content-extraction/
 * block-level data to anchor against and keep their existing coarse
 * placement.
 */

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const DIVYA_DESAMS_DIR = path.join(REPO_ROOT, "content/divya-desams");
const CONTENT_EXTRACTION_DD_DIR = path.join(REPO_ROOT, "content-extraction/divya-desams");
const REPORT_PATH = path.join(REPO_ROOT, "source-material/reports/phase-6E-image-anchors-report.md");

interface ImageEntry {
  assetId: string;
  sourceAssetUuid: string;
  placement?: string;
  placementAnchor?: string;
  [key: string]: unknown;
}

function writeRecord(file: string, record: unknown) {
  const result = DivyaDesamSchema.safeParse(record);
  if (!result.success) {
    throw new Error(`Refusing to write ${file}: fails DivyaDesamSchema validation -- ${result.error.message}`);
  }
  fs.writeFileSync(path.join(DIVYA_DESAMS_DIR, file), JSON.stringify(record, null, 2) + "\n", "utf8");
}

interface AnchorRecord {
  slug: string;
  assetId: string;
  anchor: string;
}

function run() {
  const files = fs.readdirSync(DIVYA_DESAMS_DIR).filter((f) => f.endsWith(".json")).sort();
  const applied: AnchorRecord[] = [];

  for (const file of files) {
    const record = JSON.parse(fs.readFileSync(path.join(DIVYA_DESAMS_DIR, file), "utf8"));
    const images: ImageEntry[] = record.images ?? [];
    const afterImages = images.filter((img) => img.placement === "after-sthala-puranam" && !img.assetId.includes("-book-"));
    if (afterImages.length === 0) continue;

    const anchors = computeImageAnchors(CONTENT_EXTRACTION_DD_DIR, record.migration.sourcePageId, record.sthalaPuranam);
    if (anchors.size === 0) continue;

    let changed = false;
    for (const img of afterImages) {
      const anchor = anchors.get(img.sourceAssetUuid);
      if (!anchor) continue;
      img.placementAnchor = anchor;
      changed = true;
      applied.push({ slug: record.slug, assetId: img.assetId, anchor });
    }

    if (changed) writeRecord(file, record);
  }

  const reportLines = [
    "# Phase 6E-C follow-up: sub-heading image anchors",
    "",
    "Generated by `scripts/source-material/apply-image-anchors.ts` in response to:",
    '"The positioning of the pictures is still not happening correctly" (after the earlier',
    "before/after-Sthala-Puranam split, records with several named sub-sections still lumped every",
    "\"after\" image into one undifferentiated group).",
    "",
    `## Images anchored to a specific Sthala Puranam line (${applied.length})`,
    "",
    "| Divya Desam | Image | Anchored after |",
    "|---|---|---|",
    ...applied.map((a) => `| ${a.slug} | ${a.assetId} | ${a.anchor.replace(/\|/g, "\\|")} |`),
    "",
  ];
  fs.mkdirSync(path.dirname(REPORT_PATH), { recursive: true });
  fs.writeFileSync(REPORT_PATH, reportLines.join("\n") + "\n", "utf8");

  console.log(`Applied ${applied.length} sub-heading anchors across ${new Set(applied.map((a) => a.slug)).size} records.`);
  console.log(`Report written to ${path.relative(REPO_ROOT, REPORT_PATH)}`);
}

run();
