import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runComparison } from "./extract-divyadesam-book.ts";

/**
 * Phase 6E, Part 4 -- renders the same classification
 * extract-divyadesam-book.ts computes into a human-readable Markdown
 * report for every category-C (conflict) and category-D (ambiguous)
 * finding, plus the multi-shrine records that could not be diffed at
 * all and the one book entry that could not be confidently identified.
 * Read-only: writes only the report file, never touches content/.
 */

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const OUT_PATH = path.join(REPO_ROOT, "source-material/reports/phase-6E-review-report.md");

function esc(value: string | undefined): string {
  if (!value) return "_(absent)_";
  const oneLine = value.replace(/\s+/g, " ").trim();
  const truncated = oneLine.length > 300 ? oneLine.slice(0, 300) + "…" : oneLine;
  return truncated.replace(/\|/g, "\\|");
}

function main() {
  const result = runComparison();
  const lines: string[] = [];

  lines.push("# Phase 6E — 108 Divyadesam book review report");
  lines.push("");
  lines.push(
    "Generated by `scripts/source-material/generate-review-report.ts`. Every item below was deliberately NOT auto-merged into `content/divya-desams/`. Categories follow the Phase 6E brief's Part 4 definitions (C = conflicts with the existing record, D = ambiguous/incomplete, requiring human review)."
  );
  lines.push("");

  lines.push("## Could not confidently identify (book entry with no matched record)");
  lines.push("");
  if (result.unmatchedBookEntries.length === 0) {
    lines.push("None.");
  } else {
    for (const e of result.unmatchedBookEntries) {
      lines.push(
        `- Page ${e.page}, raw captured title \`${e.rawCapturedTitle}\`. Surrounding text: Moolavar "Varadarajan", Thayaar "Sridevi Bhoodevi", Vimanam "Kanaga Vimanam", ~8km from Sirkazhi. This does not match any of the 107 existing records by name, and could not be confidently identified as a genuinely new (109th) temple vs. an alternate description of an already-covered Sirkazhi-cluster temple. **Needs human review against the physical book.**`
      );
    }
  }
  lines.push("");

  lines.push("## Multi-entry / structurally unmergeable records");
  lines.push("");
  lines.push(
    "These records are matched by MORE than one book sub-entry (multiple shrines each with their own Moolavar/Thayaar/etc.), or the book's own text triggered the same `AmbiguousLabelError` the original SAP migration hit. The schema (`content-lib/schemas/divya-desam.ts`) has exactly one flat `templeInformation` object per record — it cannot represent distinct per-shrine facts. **No merge was attempted for any field on these records.**"
  );
  lines.push("");
  const entireEntryD = result.classifications.filter((c) => c.fields.some((f) => f.field === "(entire entry)"));
  if (result.ambiguousGroups.length === 0 && entireEntryD.length === 0) {
    lines.push("None.");
  } else {
    for (const g of result.ambiguousGroups) {
      lines.push(`- **${g.displayName}** (\`${g.slug}\`) — matched by ${g.entryCount} separate book sub-entries.`);
    }
    for (const c of entireEntryD) {
      const reason = c.fields.find((f) => f.field === "(entire entry)")?.reason ?? "";
      lines.push(`- **${c.displayName}** (\`${c.slug}\`), book page ${c.bookPage} — ${reason}`);
    }
  }
  lines.push("");
  lines.push(
    "**Proposed schema extension (not implemented — Part 7 requires stopping and reporting rather than changing `content-lib/schemas/` unilaterally):** allow `shrines[]` entries to optionally carry their own `templeInformation` sub-object, so a multi-shrine record could store each shrine's Moolavar/Thayaar/etc. individually instead of requiring one ambiguous flat object. This would let the 108 Divyadesam book's genuinely per-shrine data (it DOES give clean, unambiguous fields for Tanjai Mamanikoyil's 3 sub-temples and Tiruvaali-Tirunagari's 2, just not in a shape the current schema can hold) be safely imported in a future phase."
  );
  lines.push("");

  lines.push("## Category C — conflicts (existing and source values both present, and differ)");
  lines.push("");
  lines.push("| Divya Desam | Field | Existing value | Source value | Book page |");
  lines.push("|---|---|---|---|---|");
  for (const c of result.classifications) {
    for (const f of c.fields) {
      if (f.category !== "C") continue;
      lines.push(`| ${c.displayName} (\`${c.slug}\`) | ${f.field} | ${esc(f.existingValue)} | ${esc(f.sourceValue)} | ${c.bookPage} |`);
    }
  }
  lines.push("");

  lines.push("## Category D — ambiguous / requires human comparison (both values present, judged too different to auto-classify as equivalent)");
  lines.push("");
  lines.push("| Divya Desam | Field | Overlap reasoning | Book page |");
  lines.push("|---|---|---|---|");
  for (const c of result.classifications) {
    for (const f of c.fields) {
      if (f.category !== "D" || f.field === "(entire entry)") continue;
      lines.push(`| ${c.displayName} (\`${c.slug}\`) | ${f.field} | ${esc(f.reason)} | ${c.bookPage} |`);
    }
  }
  lines.push("");

  lines.push("## Category B — supplemented (already merged into content/, see content/_provenance/divya-desams/)");
  lines.push("");
  lines.push("| Divya Desam | Field | Value added | Book page |");
  lines.push("|---|---|---|---|");
  for (const c of result.classifications) {
    for (const f of c.fields) {
      if (f.category !== "B") continue;
      lines.push(`| ${c.displayName} (\`${c.slug}\`) | ${f.field} | ${esc(f.sourceValue)} | ${c.bookPage} |`);
    }
  }
  lines.push("");

  const categoryTotals: Record<string, number> = { A: 0, B: 0, C: 0, D: 0, E: 0 };
  for (const c of result.classifications) for (const f of c.fields) categoryTotals[f.category]++;
  lines.push("## Summary");
  lines.push("");
  lines.push(`- Single-entry records compared field-by-field: ${result.classifications.length}`);
  lines.push(`- Multi-entry/unmergeable records: ${result.ambiguousGroups.length + entireEntryD.length}`);
  lines.push(`- Unmatched book entries: ${result.unmatchedBookEntries.length}`);
  lines.push(`- Field totals — A (equivalent/kept as-is): ${categoryTotals.A}, B (merged): ${categoryTotals.B}, C (conflict, flagged): ${categoryTotals.C}, D (ambiguous, flagged): ${categoryTotals.D}, E (absent from both): ${categoryTotals.E}`);
  lines.push("");

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, lines.join("\n") + "\n", "utf8");
  console.log(`Wrote ${path.relative(REPO_ROOT, OUT_PATH)}`);
}

main();
